dist: xenial
sudo: false
language: node_js
node_js: "12"
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master

before_install:
  # Correct Buildbot timezone
  - export TZ=Asia/Shanghai

script:
  # Install dependencies
  - yarn bootstrap
  # Compile and generate to site
  - yarn build

# after_success:
#   # Only trigger deployment when it's on master branch and not a pull-request
#   - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then bash .travis/deploy-ci.sh; fi

deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  keep_history: true
  commit_message: "Site updated at `date +'%Y-%m-%d %T'`"
  on:
    branch: master
