dist: xenial
sudo: false
language: node_js
node_js: "10"
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master

before_install:
  # Correct timezone
  - export TZ=Asia/Shanghai
  # Decrypt the deploy key
  - openssl aes-256-cbc -K $encrypted_e40f4962dafa_key -iv $encrypted_e40f4962dafa_iv -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
  - tar xvf .travis/secrets.tar -C ~/.ssh/ >/dev/null
  # Set the permission of the key
  - chmod 600 ~/.ssh/*.pri
  # Start SSH agent
  - eval $(ssh-agent)
  # Add deploy key to SSH agent
  - ssh-add ~/.ssh/deploy_key.pri
  # Set git config
  - git config --global user.name "h404bi"
  - git config --global user.email "h404bi@gmail.com"
  # Clone the source
  - git clone https://github.com/h404bi/www.h404bi.com.git
  - cd www.h404bi.com

script:
  # Install dependencies
  - yarn
  # Compile and generate to site
  - yarn build

after_success:
  # Clone deploy history (keep build commits)
  - git clone --depth 1 --branch gh-pages git@github.com:h404bi/www.h404bi.com.git .deploy_git
  - cd .deploy_git
  # Clear old files
  - rm -rf ./*
  # Copy new files
  - cp -r ../public/* .
  # Publish new commit to gh-pages
  - git add -A .
  - COMMITDATE=`date '+%Y-%m-%d %H:%M:%S'`
  - git commit -m "Site updated at $COMMITDATE"
  - git branch -m gh-pages
  - git push -q -u origin gh-pages
