dist: xenial
sudo: false
language: node_js
node_js: "12"
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master

before_install:
  # Correct Buildbot timezone
  - export TZ=Asia/Shanghai

script:
  - yarn build

deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  keep_history: true
  commit_message: "Site updated at `date +'%Y-%m-%d %T'`"
  on:
    branch: master
