dist: xenial
sudo: false
language: node_js
node_js: "10"
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master

before_install:
  # Make sure under HOME
  - cd $HOME
  # Correct Buildbot timezone
  - export TZ=Asia/Shanghai
  # Clone the source
  - git clone --depth=1 https://github.com/h404bi/www.h404bi.com.git website
  - cd website

script:
  # Install dependencies
  - yarn bootstrap
  # Compile and generate to site
  - yarn build

after_success:
  # Trigger deployment
  - '[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ] && ./.travis/deploy-ci.sh'
