sudo: false
language: node_js
node_js: "8"
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master

before_install:
  # Correct timezone
  - export TZ=Asia/Shanghai
  # Decrypt the deploy key
  - openssl aes-256-cbc -K $encrypted_6ede49e80280_key -iv $encrypted_6ede49e80280_iv -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
  - tar xvf .travis/secrets.tar -C ~/.ssh/ >/dev/null
  # Set the permission of the key
  - chmod 600 ~/.ssh/*.pri
  # Start SSH agent
  - eval $(ssh-agent)
  # Add the key to SSH agent
  - ssh-add ~/.ssh/deploy_key.pri
  # Set git config
  - git config --global user.name "h404bi"
  - git config --global user.email "h404bi@gmail.com"
  # Clone the source
  - git clone https://github.com/h404bi/www.h404bi.com.git
  - cd www.h404bi.com
  # Clone deploy history (keep build commits)
  - git clone -b gh-pages https://github.com/h404bi/www.h404bi.com.git .deploy_git

script:
  # Generate and deploy
  - hexo clean
  - hexo generate --deploy
