# Site
title: h404bi
subtitle: There will still be love in this world
description: 煙花已逝深紅犹存
author: h404bi
language: zh-cn
timezone: Asia/Shanghai

# URL
url: https://h404bi.com
root: /
permalink: blog/:year/:month/:day/:title.html

# Directory
skip_render:
- index.html
- 404.html

# Writing
new_post_name: :year-:month-:day-:title.md
filename_case: 1
highlight:
  enable: true
  line_number: false
  auto_detect: false

# Plugins
feed:
  type: atom
  path: blog/atom.xml
  limit: 20

toc:
  maxDepth: 1

html_minifier:
  exclude:
  minifyJS: true
  minifyCSS: true
  removeComments: false
  collapseWhitespace: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true

## docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: false
    typographer: true
  plugins:
    - markdown-it-footnote
    - markdown-it-sup
    - markdown-it-sub
    - markdown-it-abbr

# Themes
theme: type

disqus_shortname: h404bi

# Deployment
deploy:
  type: git
  repo:
    github: git@github.com:h404bi/h404bi.com.git,gh-pages
