# Site
title: Chawye Hsu, H404bi
subtitle: There will still be love in this world
description: 深紅の花火的个人网站, Personal Website of Chawye Hsu.
author: h404bi
email: h404bi@outlook.com
language: zh-cn
timezone: Asia/Shanghai

# URL
domain: h404bi.com
url: https://www.h404bi.com
root: /
permalink: blog/:year/:month/:day/:title.html

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
skip_render:
  - '**/*.html'

# Writing
new_post_name: :year-:month-:day-:title.md
default_layout: post
filename_case: 1
highlight:
  enable: true
  line_number: false
  auto_detect: false

# Pagination
## Set per_page to 0 to disable pagination
## This could be overrided by hexo-generator-index plugin
per_page: 9
pagination_dir: page

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Plugins
index_generator:
  # https://github.com/hexojs/hexo-generator-index/pull/7
  path: 'blog'
  per_page: 9
  order_by: -date
  post_filter: hidden
feed:
  type: atom
  path: blog/atom.xml
  limit: 20
sitemap:
  path: sitemap.xml
  template: sitemap.xml
html_minifier:
  exclude:
  minifyJS: true
  minifyCSS: true
  removeComments: false
  collapseWhitespace: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true
# docs: https://github.com/hexojs/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: false
    typographer: true
  plugins:
    - markdown-it-abbr
    - markdown-it-cjk-breaks
    - markdown-it-deflist
    - markdown-it-emoji
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-mark
    - markdown-it-sup
    - markdown-it-sub

# Themes
theme: mina

# Misc
disqus_shortname: h404bi
baidu_analytics_id: 25da54bb9d300c118148dcad780da73b
google_analytics_id: UA-91882040-1

# Deployment
deploy:
  type: git
  repo:
    github: git@github.com:h404bi/www.h404bi.com.git,gh-pages
