# Site
title: H404bi's Notes
subtitle: There will still be love in this world
description: 煙花已逝深紅犹存
author: h404bi
language: zh-cn
timezone: Asia/Shanghai

# URL
url: //notes.h404bi.com
root: /
permalink: posts/:title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 404.html

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Extensions
feed:
    type: atom
    path: atom.xml
    limit: 20
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
  plugins:
    - markdown-it-footnote
    - markdown-it-sup
    - markdown-it-sub
    - markdown-it-abbr

## Themes
theme: tranquilpeak

# Deployment
deploy:
  type: git
  repo:
    github: git@github.com:h404bi/notes.git,gh-pages
