# Site
title: Chawye Hsu, H404bi
subtitle: There will still be love in this world
author: h404bi
email: h404bi@gmail.com
language: zh-cn
timezone: Asia/Shanghai

# URL
domain: h404bi.com
url: https://h404bi.com
root: /
permalink: blog/:year/:month/:day/:title.html

# Directory
skip_render:
- index.html
- 404.html

# Writing
new_post_name: :year-:month-:day-:title.md
filename_case: 1
highlight:
  enable: true
  line_number: false
  auto_detect: false

# Plugins
feed:
  type: atom
  path: blog/atom.xml
  limit: 20
sitemap:
  path: sitemap.xml
  template: sitemap.xml
html_minifier:
  exclude:
  minifyJS: true
  minifyCSS: true
  removeComments: false
  collapseWhitespace: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true
## docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: false
    typographer: true
  plugins:
    - markdown-it-abbr
    - markdown-it-deflist
    - markdown-it-emoji
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-mark
    - markdown-it-sup
    - markdown-it-sub

# Themes
theme: type

# Misc
disqus_shortname: h404bi
google_analytics_id: UA-91882040-1

# Deployment
deploy:
  type: git
  repo:
    github: git@github.com:h404bi/h404bi.com.git,gh-pages
